stello/crm/urls.py
from django.urls import path
from . import views
app_name = 'crm'
urlpatterns = [
    path('worker/', views.WorkerListView.as_view(), name="worker_list"),
    path('worker/<int:worker_id>', views.WorkerUpdateView.as_view(),
         name="worker_update"),
    path('worker/create/', views.WorkerCreateView.as_view(),
         name="worker_create"),
    path('order/', views.OrderListView.as_view(), name="order"),
    path('order/<int:customer_id>', views.OrderDetailView.as_view(),
         name="order_detail"),
    path('order/create/', views.OrderCreateView.as_view(),
         name="order_create"),
    path('integration/list/', views.IntegrationListView.as_view(),
         name="integration_list"),
    path('integration/create/', views.IntegrationCreateView.as_view(),
         name="integration_create"),
    path('integration/<int:id>', views.IntegrationDetailView.as_view(),
         name="integration_detail"),
    path('report/list/', views.ReportListView.as_view(),
         name="report_list"),
    path('report/list/<int:manager>', views.ReportListView.as_view(),
         name="report_list")
]

stello/stello/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    url('', include('pwa.urls')),
    path('', auth_views.LoginView.as_view(
        redirect_authenticated_user=True),name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),
    path('figma/', include('figma.urls')),
    path('crm/', include('crm.urls')),
    path('social_messenger/', include('social_messenger.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

stello/crm/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Order, Сustomer, Profile, Integration


# Форма пользователя
class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = [
            'username', 'password', 'first_name', 'last_name', 'email'
        ]

        def __init__(self, request, *args, **kwargs):
            self.request = request
            super().__init__(*args, **kwargs)

        def save(self, commit=True):
            instance = super().save(commit=False)
            instance.company = self.request.user.profile.company
            if commit:
                instance.save()
            return instance


# Форма работника
class WorkerForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = [
            'phone_number', 'address', 'type', 'is_blocked'
        ]


# Форма заказа
class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = [
            'product', 'count', 'payment', 'deadline_date', 'price'
        ]

    def __init__(self, request, *args, **kwargs):
        self.request = request
        super().__init__(*args, **kwargs)

    def save(self, commit=True):
        instance = super().save(commit=False)
        instance.seller = self.request.user
        instance.company = self.request.user.profile.company
        if commit:
            instance.save()
        return instance


# Форма клиента
class СustomerForm(forms.ModelForm):
    class Meta:
        model = Сustomer
        fields = [
            'login', 'phone_number', 'address', 'backup_phone_number'
        ]

    def __init__(self, request, *args, **kwargs):
        self.request = request
        super().__init__(*args, **kwargs)

    def save(self, commit=True):
        instance = super().save(commit=False)
        instance.company = self.request.user.profile.company
        if commit:
            instance.save()
        return instance


# Форма интеграции
class IntegrationForm(forms.ModelForm):
    class Meta:
        model = Integration
        fields = [
            'type', 'login', 'externalId',  'api_id', 'api_token'
        ]

    def __init__(self, request, *args, **kwargs):
        self.request = request
        super().__init__(*args, **kwargs)

    def save(self, commit=True):
        instance = super().save(commit=False)
        instance.company = self.request.user.profile.company
        if commit:
            instance.save()
        return instance

stello/crm/views.py
from django.shortcuts import redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.base import TemplateResponseMixin, View
from django.contrib.auth.models import User
from django.views.generic.list import ListView
from django.shortcuts import get_object_or_404
from .models import Profile, Integration, Order, Сustomer, Lead,\
    CompanyLeadStatus
from .forms import WorkerForm, UserForm, IntegrationForm,\
    OrderForm, СustomerForm


class WorkerMixin(LoginRequiredMixin, TemplateResponseMixin, View):
    worker_form_class = WorkerForm
    user_form_class = UserForm

    def get_workers(self, request, company):
        workers = User.objects.filter(profile__company=company).all()
        return workers

    def integ_account_save(self, request, user_save):
        accounts = request.POST.getlist('integration_account')
        user_save.integration_set.clear()
        for account in accounts:
            integration = Integration.objects.get(pk=account)
            integration.managers.add(user_save)
        return True


# Страница списка работников
class WorkerListView(WorkerMixin):
    template_name = 'crm/worker/list.html'

    def get(self, request, *args, **kwargs):
        company = self.request.user.profile.company
        workers = self.get_workers(request, company)
        return self.render_to_response({'workers': workers})


# Страница детальной информации работника
class WorkerUpdateView(WorkerMixin):
    template_name = 'crm/worker/form.html'

    def dispatch(self, *args, **kwargs):
        worker_id = self.kwargs.get('worker_id')
        company = self.request.user.profile.company
        self.workers = self.get_workers(self.request, company)
        self.worker = get_object_or_404(
            User, pk=worker_id)
        self.profile = get_object_or_404(Profile, user=self.worker)
        self.integrations = Integration.objects.filter(
            company=company).all()
        return super().dispatch(*args, **kwargs)

    def get(self, request, *args, **kwargs):
        worker_form = self.worker_form_class(instance=self.profile)
        user_form = self.user_form_class(instance=self.worker)
        return self.render_to_response({
            'workers': self.workers, 'worker': self.worker,
            'worker_form': worker_form, 'user_form': user_form,
            'integrations': self.integrations})

    def post(self, request, *args, **kwargs):
        worker_form = self.worker_form_class(
            request.POST, instance=self.profile)
        user_form = self.user_form_class(
            request.POST, instance=self.worker)
        if worker_form.is_valid() and user_form.is_valid():
            worker_form.save()
            user_save = user_form.save()
            self.integ_account_save(request, user_save)
            return redirect('crm:worker_update', user_save.id)
        return self.render_to_response({
            'workers': self.workers, 'worker': self.worker,
            'worker_form': worker_form, 'user_form': user_form,
            'integrations': self.integrations})


# Создать нового работника компании
class WorkerCreateView(WorkerMixin):
    template_name = 'crm/worker/form.html'

    def dispatch(self, *args, **kwargs):
        self.company = self.request.user.profile.company
        self.workers = self.get_workers(self.request, self.company)
        self.integrations = Integration.objects.filter(
            company=self.company).all()
        return super().dispatch(*args, **kwargs)

    def get(self, request, *args, **kwargs):
        worker_form = self.worker_form_class()
        user_form = self.user_form_class()
        return self.render_to_response({
            'workers': self.workers, 'integrations': self.integrations,
            'worker_form': worker_form, 'user_form': user_form
        })

    def post(self, request, *args, **kwargs):
        worker_form = self.worker_form_class(request.POST)
        user_form = self.user_form_class(request.POST)
        if worker_form.is_valid() and user_form.is_valid():
            username = request.POST.get('username')
            email = request.POST.get('email')
            password = request.POST.get('password')
            first_name = request.POST.get('first_name')
            last_name = request.POST.get('last_name')
            new_user = User.objects.create_user(
                username, email, password,
                first_name=first_name,
                last_name=last_name,
            )
            worker_form_save = worker_form.save(commit=False)
            worker_form_save.user = new_user
            worker_form_save.company = self.company
            worker_form_save.save()
            self.integ_account_save(request, new_user)
            return redirect('crm:worker_update', new_user.id)
        return self.render_to_response({
            'workers': self.workers, 'worker_form': worker_form,
            'user_form': user_form, 'integrations': self.integrations})


class OrderMixin(LoginRequiredMixin, TemplateResponseMixin, View):
    order_form_class = OrderForm
    customer_form_class = СustomerForm

    def get_customers(self, request, company):
        customers = Order.objects.filter(
            company=company).distinct('customer').all()
        return customers


# Страница списка работников
class OrderListView(OrderMixin):
    template_name = 'crm/order/list.html'

    def get(self, request, *args, **kwargs):
        company = self.request.user.profile.company
        self.customers = self.get_customers(request, company)
        return self.render_to_response({'customers': self.customers})


# Страница списка работников
class OrderDetailView(OrderMixin):
    template_name = 'crm/order/detail.html'

    def dispatch(self, *args, **kwargs):
        customer_id = self.kwargs.get('customer_id')
        self.company = self.request.user.profile.company
        self.customers = self.get_customers(self.request, self.company)
        self.customer = get_object_or_404(
            Сustomer, pk=customer_id, company=self.company)
        return super().dispatch(*args, **kwargs)

    def get(self, request, *args, **kwargs):
        orders = Order.objects.filter(customer=self.customer).all()
        customer_form = self.customer_form_class(
            request, instance=self.customer)
        order_form = self.order_form_class(request)
        return self.render_to_response({
            'customer': self.customer, 'customers': self.customers,
            'orders': orders, 'customer_form': customer_form,
            'order_form': order_form})

    def post(self, request, *args, **kwargs):
        order_form = self.order_form_class(request, data=request.POST)
        if order_form.is_valid():
            instance = order_form.save(commit=False)
            instance.customer = self.customer
            instance.seller = self.request.user
            instance.company = self.company
            instance.save()
            return redirect('crm:order_detail', self.customer.id)
        return self.render_to_response({'order_form': order_form})


# Страница списка работников
class OrderCreateView(OrderMixin):
    template_name = 'crm/order/create.html'

    def dispatch(self, *args, **kwargs):
        self.company = self.request.user.profile.company
        self.customers = self.get_customers(self.request, self.company)
        return super().dispatch(*args, **kwargs)

    def get(self, request, *args, **kwargs):
        customer_form = self.customer_form_class(request)
        order_form = self.order_form_class(request)
        return self.render_to_response({
            'customers': self.customers, 'customer_form': customer_form,
            'order_form': order_form})

    def post(self, request, *args, **kwargs):
        customer_form = self.customer_form_class(request, data=request.POST)
        order_form = self.order_form_class(request, data=request.POST)
        if customer_form.is_valid() and order_form.is_valid():
            customer = customer_form.save()
            order = order_form.save(commit=False)
            order.customer = customer
            order.save()
            return redirect('crm:order_detail', customer.id)
        return self.render_to_response({
            'customers': self.customers, 'customer_form': customer_form,
            'order_form': order_form})

class IntegrationMixin(View, TemplateResponseMixin, LoginRequiredMixin):
    form_class = IntegrationForm

    def get_integrations(self, request, company):
        customers = Integration.objects.filter(
            company=company).all()
        return customers

# Страница списка работников
class IntegrationListView(ListView, LoginRequiredMixin):
    template_name = 'crm/integration/list.html'
    model = Integration
    context_object_name = 'integrations'
    
    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(company=self.request.user.profile.company)

class IntegrationCreateView(IntegrationMixin):
    template_name = 'crm/integration/form.html'

    def dispatch(self, *args, **kwargs):
        self.company = self.request.user.profile.company
        self.integrations = self.get_integrations(
            self.request, self.company)
        return super().dispatch(*args, **kwargs)

    def get(self, request, *args, **kwargs):
        form = self.form_class(request)
        return self.render_to_response({
            'integrations': self.integrations, 'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request, data=request.POST)
        if form.is_valid():
            integration = form.save()
            return redirect('crm:integration_detail', integration.id)

stello/templates/crm/integration/form.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block sidebar %}
    {% include "crm/integration/sidebar.html" %}
{% endblock %}
{% block main %}

    <main class="main main-visible" id="MainContent">
        <!-- Profile Settings Start -->
        <div class="profile" style="display: block;">
            <div class="page-main-heading sticky-top py-2 px-3 mb-3">
                <!-- Chat Back Button (Visible only in Small Devices) -->
                <button class="btn btn-secondary btn-icon btn-minimal btn-sm text-muted d-xl-none" type="button" data-close="">
                    <svg class="hw-20" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 19l-7-7m0 0l7-7m-7 7h18"></path>
                      </svg>
                    <!-- <img class="injectable hw-20" src="./../assets/media/heroicons/outline/arrow-left.svg" alt=""> -->
                </button>

                <div class="pl-2 pl-xl-0">
                    <h5 class="font-weight-semibold">Настройки</h5>
                    <p class="text-muted mb-0">Обновить интеграцию</p>
                </div>
            </div>
            <div class="container-xl px-2 px-sm-3">
                <form action="" method="POST">
                    {% csrf_token %}
                    <div class="card mb-3">
                            <div class="card-header">
                                <h6 class="mb-1">Список интеграции</h6>
                                <p class="mb-0 text-muted small">Обновить интеграцию</p>
                            </div>
                            
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-md-6 col-12">
                                        <div class="form-group">
                                            <label for="">Название интеграции</label>
                                            {{form.login|add_class:"form-control"}}
                                        </div>
                                    </div>
                                    <div class="col-md-6 col-12">
                                        <div class="form-group">
                                            <label for="">Тип интеграции</label>
                                            {{form.type|add_class:"form-control"}}
                                        </div>
                                    </div>
                                    <div class="col-md-6 col-12">
                                        <div class="form-group">
                                            <label for="">Логин интеграции</label>
                                            {{form.externalId|add_class:"form-control"}}
                                        </div>
                                    </div>
                                    <div class="col-md-6 col-12">
                                        <div class="form-group">
                                            <label for="">Уникальный номер интеграции</label>
                                            {{form.api_id|add_class:"form-control"}}
                                        </div>
                                    </div>
                                    <div class="col-md-6 col-12">
                                        <div class="form-group">
                                            <label for="">Token интеграции</label>
                                            {{form.api_token|add_class:"form-control"}}
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="card-footer d-flex justify-content-end">
                                <input type="submit" class="btn btn-primary" name="submit" value="Сохранить изменения">
                            </div>
                        </div>
                    
                </form>
            </div>
        </div>
        <!-- Profile Settings End -->
    </main>
{% endblock %}

stello/templates/crm/integration/list.html
{% extends "base.html" %}
{% block sidebar %}
    {% include "crm/integration/sidebar.html" %}
{% endblock %}
{% block main %}
    <main class="main" id="MainContent">
        <div class="profile" style="display: block;">
            <div class="container-xl px-2 px-sm-3">
                <div class="d-flex flex-column justify-content-center text-center vh-100 w-100">
                    <div class="container">
                        <div class="avatar avatar-lg mb-2">
                            <svg height="80" width="80" viewBox="0 0 512 511"><g><path d="m120.65625 512.476562c-7.25 0-14.445312-2.023437-20.761719-6.007812-10.929687-6.902344-17.703125-18.734375-18.117187-31.660156l-1.261719-41.390625c-51.90625-46.542969-80.515625-111.890625-80.515625-183.992188 0-68.816406 26.378906-132.101562 74.269531-178.199219 47.390625-45.609374 111.929688-70.726562 181.730469-70.726562s134.339844 25.117188 181.730469 70.726562c47.890625 46.097657 74.269531 109.382813 74.269531 178.199219 0 68.8125-26.378906 132.097657-74.269531 178.195313-47.390625 45.609375-111.929688 70.730468-181.730469 70.730468-25.164062 0-49.789062-3.253906-73.195312-9.667968l-46.464844 20.5c-5.035156 2.207031-10.371094 3.292968-15.683594 3.292968zm135.34375-471.976562c-123.140625 0-216 89.816406-216 208.925781 0 60.667969 23.957031 115.511719 67.457031 154.425781 8.023438 7.226563 12.628907 17.015626 13.015625 27.609376l.003906.125 1.234376 40.332031 45.300781-19.988281c8.15625-3.589844 17.355469-4.28125 25.921875-1.945313 20.132812 5.554687 41.332031 8.363281 63.066406 8.363281 123.140625 0 216-89.816406 216-208.921875 0-119.109375-92.859375-208.925781-216-208.925781zm-125.863281 290.628906 74.746093-57.628906c5.050782-3.789062 12.003907-3.839844 17.101563-.046875l55.308594 42.992187c16.578125 12.371094 40.304687 8.007813 51.355469-9.433593l69.519531-110.242188c6.714843-10.523437-6.335938-22.417969-16.292969-14.882812l-74.710938 56.613281c-5.050781 3.792969-12.003906 3.839844-17.101562.046875l-55.308594-41.988281c-16.578125-12.371094-40.304687-8.011719-51.355468 9.429687l-69.554688 110.253907c-6.714844 10.523437 6.335938 22.421874 16.292969 14.886718zm0 0" data-original="#000000" class="active-path" data-old_color="#000000" fill="#665dfe"></path></g> </svg>
                        </div>

                        <h5><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Добро пожаловать!</font></font></h5>
                        <p class="text-muted"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
                            Пожалуйста, выберите интеграцию
                        </font></font></p>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

stello/templates/crm/integration/sidebar.html
{% load static %}
{% load crm_tags %}
<!-- Tab Content Start -->
<div class="tab-content">
    <!-- Profile Tab Content Start -->
    <div>
        <div class="d-flex flex-column h-100">
            <div class="hide-scrollbar">
                <!-- Sidebar Header Start -->
                <div class="sidebar-header sticky-top p-2">
                    <h5 class="font-weight-semibold">Интеграции</h5>
                    <p class="text-muted mb-0">Список интеграции и настройки</p>
                </div>
                <!-- Sidebar Header end -->

                <!-- Sidebar Content Start -->
                <ul class="contacts-list" id="callLogTab" data-call-list="">
                    <li class="contacts-item worker-select">
                        <a class="contacts-link" href="{% url 'crm:integration_create' %}">
                            <div class="contacts-content">
                                <div class="contacts-info">
                                    <h6 class="chat-name text-truncate">Добавить новой интеграции</h6>
                                </div>
                            </div>
                        </a>
                    </li>
                    <!-- workers Item Start -->
                    {% for value in integrations %}
                        <li class="contacts-item worker-select {% is_active value.id integration.id %}" data-id="{{value.id}}">
                            <a class="contacts-link" href="{% url 'crm:integration_detail' value.id %}">
                                <div class="avatar">
                                    <img src="{% static 'images/social.png' %}" alt="">
                                </div>
                                <div class="contacts-content">
                                    <div class="contacts-info">
                                        <h6 class="chat-name text-truncate">{{value.login}}</h6>
                                    </div>
                                    <div class="contacts-texts">
                                        <!-- Default :: Inline SVG -->
                                        <svg class="hw-16 text-muted mr-1" viewBox="0 0 20 20" fill="currentColor">
                                            <path fill-rule="evenodd" d="M5.05 4.05a7 7 0 119.9 9.9L10 18.9l-4.95-4.95a7 7 0 010-9.9zM10 11a2 2 0 100-4 2 2 0 000 4z" clip-rule="evenodd"></path>
                                        </svg>
                                            
                                        <!-- Alternate :: External File link -->
                                        <!-- <img class="injectable hw-16 text-muted mr-1" src="./../assets/media/heroicons/solid/location-marker.svg" alt=""> -->
                                        <p class="text-muted mb-0">{{value.type}}</p>
                                    </div>
                                </div>
                            </a>
                        </li>
                    {% endfor %}
                </ul>
                <!-- Sidebar Content End -->

            </div>
        </div>
    </div>
    <!-- Profile Tab Content End -->
</div>
<!-- Tab Content End -->