stello/crm/urls.py
from django.urls import path
from . import views
app_name = 'crm'
urlpatterns = [
    path('worker/', views.WorkerListView.as_view(), name="worker_list"),
    path('worker/<int:worker_id>', views.WorkerUpdateView.as_view(),
         name="worker_update"),
    path('worker/create/', views.WorkerCreateView.as_view(),
         name="worker_create"),
    path('order/', views.OrderListView.as_view(), name="order"),
    path('order/<int:customer_id>', views.OrderDetailView.as_view(),
         name="order_detail"),
    path('order/create/', views.OrderCreateView.as_view(),
         name="order_create"),
    path('integration/list/', views.IntegrationListView.as_view(),
         name="integration_list"),
    path('integration/create/', views.IntegrationCreateView.as_view(),
         name="integration_create"),
    path('integration/<int:id>', views.IntegrationDetailView.as_view(),
         name="integration_detail"),
    path('report/list/', views.ReportListView.as_view(),
         name="report_list"),
    path('report/list/<int:manager>', views.ReportListView.as_view(),
         name="report_list")
]

stello/figma/urls.py
from django.urls import path
from . import views
app_name = 'figma'
urlpatterns = [
    # Сайт клиента
    path('<int:seller>/', views.IndexView.as_view(), name='index'),
    path('<int:seller>/<int:category>', views.IndexView.as_view(),
         name='index'),
    path('product/<int:seller>/<id>', views.ProductDetailView.as_view(),
         name='product_detail'),
    # Сайт конструктор сайта
    path('constructor/', views.ConstructorIndexView.as_view(),
         name='constructor_index'),
    path('constructor/product/<int:id>',
         views.ConstructorProductDetailView.as_view(),
         name='constructor_product_detail'),
    path('constructor/product_photo/<int:id>',
         views.ConstructorProductPhotoDetailView.as_view(),
         name='constructor_product_photo_detail'),
]

stello/stello/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    url('', include('pwa.urls')),
    path('', auth_views.LoginView.as_view(
        redirect_authenticated_user=True),name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),
    path('figma/', include('figma.urls')),
    path('crm/', include('crm.urls')),
    path('social_messenger/', include('social_messenger.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

stello/figma/models.py
from django.db import models
from django.conf import settings
from tinymce.models import HTMLField


# Базовый абстрактный класс
class ItemBase(models.Model):
    title = models.CharField(max_length=180)

    class Meta:
        abstract = True

    def __str__(self):
        return self.title


# Список категории
class Сategory(ItemBase):
    seller = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE
    )

    class Meta:
        db_table = "figma_categories"


# материалы
class Material(ItemBase):
    pass

    class Meta:
        db_table = "figma_materials"


# Связь материала с продуктом М-М
class ProductMaterial(models.Model):
    material = models.ForeignKey(Material,
                                 related_name='rel_material',
                                 on_delete=models.CASCADE)
    product = models.ForeignKey('Product',
                                related_name='rel_product',
                                on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=0)

    class Meta:
        db_table = "figma_products_materials"

    def __str__(self):
        return f'{self.material} rel {self.product}'


# список товаров
class Product(ItemBase):
    seller = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    KIND_CHOICES = [
        ('normal', 'Обычный'),
        ('text_input', 'Набор текста'),
        ('image_select', 'Выбор изображения')
    ]
    category = models.ForeignKey(Сategory,
                                 related_name='products_category',
                                 on_delete=models.CASCADE)
    file = models.FileField(upload_to='images')
    file_extra1 = models.FileField(
        upload_to='images', blank=True, null=True)
    file_extra2 = models.FileField(
        upload_to='images', blank=True, null=True)
    file_extra3 = models.FileField(
        upload_to='images', blank=True, null=True)
    description = HTMLField(blank=True, null=True)
    details = HTMLField(blank=True, null=True)
    shipping_return = HTMLField(blank=True, null=True)
    price = models.DecimalField(max_digits=10, decimal_places=0)
    price_old = models.DecimalField(max_digits=10, decimal_places=0,
                                    blank=True, null=True)
    is_top = models.BooleanField(default=False)
    kind = models.CharField(
        max_length=12,
        choices=KIND_CHOICES,
        default='normal'
    )
    classes = models.CharField(max_length=180, blank=True)
    materials = models.ManyToManyField(Material,
                                       through='ProductMaterial',
                                       related_name='rel_materials')

    class Meta:
        db_table = "figma_products"

stello/figma/forms.py
from django import forms
from .models import Сategory, Product, ProductMaterial


# Форма категории
class CategoryForm(forms.ModelForm):
    class Meta:
        model = Сategory
        fields = ['title', 'seller']


# Форма продукта
class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = '__all__'

    def __init__(self, user, *args, **kwargs):
        super(ProductForm, self).__init__(*args, **kwargs)
        self.fields['category'].queryset = Сategory.objects.filter(
            seller=user.id)


# Форма материала продукта
class ProductMaterialForm(forms.ModelForm):
    class Meta:
        model = ProductMaterial
        fields = '__all__'


# Форма заказа продукта
class ProductOrderForm(forms.Form):
    pass

stello/figma/views.py
import uuid
from django.shortcuts import redirect, render
from django.views.generic import TemplateView
from django.views.generic.base import TemplateResponseMixin, View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
from django.contrib.auth.models import User
from .models import Сategory, Product, ProductMaterial, Material
from .forms import CategoryForm, ProductForm
from crm.models import Сustomer
from social_messenger.models import Message
from crm.forms import OrderForm, СustomerForm


# List views
class IndexView(TemplateView):
    template_name = 'figma/client-site/index.html'

    def get(self, request, *args, **kwargs):
        seller = get_object_or_404(User, id=self.kwargs['seller'])
        Message.objects.create(lead_id=12,
                               message="{\"text\": \"\\u0425\\u043e\\u0440\\u043e\\u0448\\u043e \\u0436\\u0434\\u0451\\u043c\"}")
        kwargs.setdefault("seller", seller)
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        seller = self.kwargs['seller']
        client_auth = self.request.session.get('client_auth')
        if not client_auth:
            client_auth = self.request.session['client_auth'] = str(
                uuid.uuid4())
        category = self.kwargs.get('category', None)
        context['categories'] = Сategory.objects.filter(
            seller=seller).all()
        context['client_auth'] = client_auth
        if not category:
            context['products'] = Product.objects.filter(
                is_top=True, seller=seller)[:12]
        else:
            context['category'] = get_object_or_404(Сategory, id=category)
            context['products'] = Product.objects.filter(
                category__id=category, seller=seller)[:12]
        return context


# Детальный просмотр продукта
class ProductDetailView(TemplateResponseMixin, View):
    template_name = 'figma/client-site/product_text_detail.html'
    order_form_class = OrderForm
    сustomer_form_class = СustomerForm
    context = {}

    def dispatch(self, *args, **kwargs):
        product_id = self.kwargs['id']
        self.context['seller'] = get_object_or_404(
            User, id=self.kwargs['seller'])
        client_auth = self.request.session.get('client_auth')
        if not client_auth:
            client_auth = self.request.session['client_auth'] = str(
                uuid.uuid4())
        self.context['client_auth'] = client_auth
        self.context['product'] = get_object_or_404(Product, id=product_id)
        self.context['product_materials'] = ProductMaterial.objects.filter(
            product__id=product_id).all()
        return super().dispatch(*args, **kwargs)

    def get(self, request, *args, **kwargs):
        return self.render_to_response(self.context)

    def post(self, request, *args, **kwargs):
        order_form = self.order_form_class(request.POST)
        сustomer_form = self.сustomer_form_class(request.POST)
        if order_form.is_valid() and сustomer_form.is_valid():
            obj_customer, created = Сustomer.objects.get_or_create(
                account=self.context['client_auth'],
                defaults={
                    'phone_number': request.POST.get('phone_number')
                },
            )
            obj_order = order_form.save(commit=False)
            obj_order.customer = obj_customer
            obj_order.seller = self.context['seller']
            obj_order.save()
            return redirect('figma:index', self.kwargs['seller'])
        self.context['order_form'] = order_form
        self.context['сustomer_form'] = сustomer_form
        return self.render_to_response(self.context)


# Главная страница менеджера
class ConstructorIndexView(LoginRequiredMixin, TemplateResponseMixin, View):
    template_name = 'figma/constructor-site/index.html'
    category_form_class = CategoryForm
    product_form_class = ProductForm
    auth_categories = None
    products = None
    product = None
    category = None

    def dispatch(self, *args, **kwargs):
        self.categories = Сategory.objects.filter(
            seller=self.request.user.id).all()
        self.products = Product.objects.filter(
            is_top=True, seller=self.request.user.id)[:12]
        return super().dispatch(*args, **kwargs)

    def get(self, request, *args, **kwargs):
        if request.is_ajax():
            if request.GET.get('product_edit', None):
                self.product = get_object_or_404(
                    Product, id=request.GET.get('product_id'))
                return render(
                    request, 'figma/constructor-site/product_modal.html',
                    {'product_form': self.product_form_class(
                        request.user, instance=self.product),
                     'product': self.product})
            elif request.GET.get('category_edit', None):
                self.category = get_object_or_404(
                    Сategory, id=request.GET.get('category_id'))
                return render(
                    request, 'figma/constructor-site/category_modal.html',
                    {'category_form': self.category_form_class(
                        instance=self.category),
                     'category': self.category})
            elif request.GET.get('category_remove', None):
                self.category = get_object_or_404(
                    Сategory, id=request.GET.get('category_id'))
                return render(
                    request,
                    'figma/constructor-site/category_remove_modal.html',
                    {'category': self.category})
            elif request.GET.get('product_remove', None):
                self.product = get_object_or_404(
                    Product, id=request.GET.get('product_id'))
                return render(
                    request,
                    'figma/constructor-site/product_remove_modal.html',
                    {'product': self.product})
        return self.render_to_response(
            {
                'category_form': self.category_form_class(),
                'product_form': self.product_form_class(request.user),
                'categories': self.categories,
                'products': self.products,
                'product': self.product,
                'category': self.category
            })

    def post(self, request, *args, **kwargs):
        if request.POST.get('category-submit', None):
            category_id = request.POST.get('category_id', None)
            if category_id:
                category = get_object_or_404(Сategory, id=category_id)
                category_form = self.category_form_class(
                    request.POST, instance=category)
            else:
                category_form = self.category_form_class(request.POST)
            if category_form.is_valid():
                category_form.save()
        elif request.POST.get('product-submit', None):
            product_id = request.POST.get('product_id', None)
            if product_id:
                product = get_object_or_404(Product, id=product_id)
                product_form = self.product_form_class(
                    request.user, request.POST,
                    request.FILES, instance=product)
            else:
                product_form = self.product_form_class(
                    request.user, request.POST, request.FILES)
            if product_form.is_valid():
                product_form.save()
            else:
                print(product_form.errors)
        elif request.POST.get('category-remove-submit', None):
            Сategory.objects.filter(id=request.POST.get(
                'category_id'), seller=request.user.id).delete()
        elif request.POST.get('product-remove-submit', None):
            Product.objects.filter(id=request.POST.get(
                'product_id'), seller=request.user.id).delete()
        return redirect('figma:constructor_index')


# Mixin продукта
class ConstructorProductMixin(LoginRequiredMixin, TemplateResponseMixin, View):
    product_form_class = ProductForm
    product = None
    product_materials = None

    def dispatch(self, *args, **kwargs):
        self.product = get_object_or_404(
            Product, id=self.kwargs['id'])
        self.product_materials = ProductMaterial.objects.filter(
            product=self.kwargs['id']).all()
        return super().dispatch(*args, **kwargs)

    def post(self, request, *args, **kwargs):
        product_form = self.product_form_class(
            request.user, request.POST,
            request.FILES, instance=self.product)
        if product_form.is_valid():
            product_form.save()
            for material, price in zip(
                    request.POST.getlist('material_title'),
                    request.POST.getlist('material_price')):
                if material and price:
                    obj, created = Material.objects.get_or_create(
                        title=material)
                    q = ProductMaterial(material=obj, product=self.product,
                                        price=price)
                    q.save()
            if request.POST.get('send-material', None):
                return redirect('figma:constructor_product_detail',
                                self.kwargs['id'])
            return redirect('figma:constructor_index')
        return self.render_to_response({
            'product': self.product, 'product_form': product_form,
            'product_materials': self.product_materials})


# Детальная информация текстового продукта
class ConstructorProductDetailView(ConstructorProductMixin):

stello/templates/figma/client-site/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
    {% load pwa %}
    <title></title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- css файлы -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/figma/client_site.css' %}"/>

    <!-- js файлы -->
    <script type="text/javascript" src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/figma/jquery.slicknav.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/figma/jquery.nicescroll.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/figma/owl.carousel.min.js' %}"></script>
    
    <script type="text/javascript" src="{% static 'js/figma/main.js' %}"></script>

    
    {% progressive_web_app_meta %}
  </head>
  <body>
    <!-- Page Preloder -->
    <div id="preloder">
      <div class="loader"></div>
    </div>

    <!-- Header section -->
    <header class="header-section">
      <div class="header-top">
        <div class="container">
          <div class="row">
            <div class="col-lg-12 text-center">
              <!-- logo -->
              <a href="" class="site-logo">
                <img src="" alt="">
              </a>
            </div>
            <!--div class="col-xl-6 col-lg-5">
              <form class="header-search-form">
                <input type="text" placeholder="Поиск товара ....">
                <button><i class="flaticon-search"></i></button>
              </form>
            </div-->
          </div>
        </div>
      </div>
      <nav class="main-navbar">
        <div class="container">
          <!-- menu -->
          <ul class="main-menu">
            <li><a href="#">Главная страница</a></li>
            <!--li><a href="#">Для парня / отца</a></li>
            <li><a href="#">Для девушки / мамы</a></li>
            <li><a href="#">для новорожденного</a></li-->
          </ul>
        </div>
      </nav>
    </header>
    <!-- Header section end -->
    {% block content %}{% endblock %}
    <!-- Footer section -->
    <section class="footer-section">
      <div class="social-links-warp">
        <div class="container">
          <div class="social-links">
            <a href="" class="instagram"><i class="fa fa-instagram"></i><span>instagram</span></a>
            <a href="" class="google-plus"><i class="fa fa-google-plus"></i><span>g+plus</span></a>
            <a href="" class="pinterest"><i class="fa fa-pinterest"></i><span>pinterest</span></a>
            <a href="" class="facebook"><i class="fa fa-facebook"></i><span>facebook</span></a>
            <a href="" class="twitter"><i class="fa fa-twitter"></i><span>twitter</span></a>
            <a href="" class="youtube"><i class="fa fa-youtube"></i><span>youtube</span></a>
            <a href="" class="tumblr"><i class="fa fa-tumblr-square"></i><span>tumblr</span></a>
          </div>
        </div>
      </div>
    </section>
    <!-- Footer section end -->
    <script type="text/javascript">
      $(document).ready(function(){
        {% block domready %}
        {% endblock %}
      });  
    </script>
  </body>
</html>

stello/templates/figma/client-site/index.html
{% extends "figma/client-site/base.html" %}
{% load static %}
{% block content %}
	<section class="category-section spad">
		<div class="container">
			<div class="row">
			
				<div class="col-lg-3 order-1 order-lg-1">
					<div class="filter-widget">
						<h2 class="fw-title">Категории</h2>
						<ul class="category-menu">
							{% for  category in categories %}
								<li>
									<a href="{% url 'figma:index' seller=seller category=category.id %}">{{category.title}}</a>
								</li>
							{% empty %}
							<li>
								<a href="">Категории не добавлены</a>
							</li>
							{% endfor %}
						</ul>
					</div>
				</div>

				<div class="col-lg-9  order-2 order-lg-2 mb-5 mb-lg-0">
					<div class="row">
						<div class="col-lg-12">
							<div class="text-center">
								<h2 class="border-b">
									{% if category %}
										{{category.title}}
									{% else %}
										Топ продаж
									{% endif %}
								</h2>
							</div>
						</div>
						{% for product in products %}
							<div class="col-lg-4 col-sm-6">
								<div class="product-item">
									<div class="pi-pic">
										{% if product.price_old %}
											<div class="tag-sale">Акция</div>
										{% endif %}
										<a href="{% url 'figma:product_detail' seller=seller id=product.id %}">
											<img src="{{product.file.url}}" alt="">
										</a>
										<div class="pi-links">
											<a href="#" class="wishlist-btn"><i class="fa fa-heart-o" aria-hidden="true"></i></a>
										</div>
									</div>
									<div class="pi-text">
										<span class="span-tg" style="color:#e81150;font-weight: bold;">{{product.price}} тг</span>
										{% if product.price_old %}
											<del>{{product.price_old}} тг</del>
										{% endif %}
										<p style="color:#9a9a9a;">{{product.title}}</p>
									</div>
								</div>
							</div>
						{% endfor %}
					</div>
				</div>
			</div>
		</div>
	</section>
{% endblock %}

stello/templates/figma/client-site/product_text_detail.html
{% extends "figma/client-site/base.html" %}
{% load static %}
{% block content %}
	<!-- product section -->
	<section class="product-section">
		<div class="container">
			<div class="row">
				<div class="col-lg-6">
					<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
					  <div class="carousel-inner">
						<div class="carousel-item active">
						  <img src="{{product.file.url}}" alt="...">
						</div>
						{% if product.file_extra1 %}
							<div class="carousel-item">
							  <img src="{{product.file_extra1.url}}" alt="...">
							</div>
						{% endif %}
						{% if product.file_extra2 %}
							<div class="carousel-item">
							  <img src="{{product.file_extra2.url}}" alt="...">
							</div>
						{% endif %}
						{% if product.file_extra3 %}
							<div class="carousel-item">
							  <img src="{{product.file_extra3.url}}" alt="...">
							</div>
						{% endif %}
					  </div>
					  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
						<span class="carousel-control-prev-icon" aria-hidden="true"></span>
						<span class="sr-only">Previous</span>
					  </a>
					  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
						<span class="carousel-control-next-icon" aria-hidden="true"></span>
						<span class="sr-only">Next</span>
					  </a>
					</div>
				</div>
				<div class="col-lg-6 product-details">
					<h2 class="p-title" style="font-weight: 400;">{{product.title}}</h2>
					<h3 class="p-price" id="price-content" style="font-weight: 600;">
						<input type="hidden" name="product" id="product" value="{{product.id}}">
						{{product.price}} тг
						{% if product.price_old %}
							<del style="color: #de0047;font-weight: 600;margin-left: 5px;font-size: 18px;">
								{{product.price_old}} тг
							</del>
						{% endif %}
					</h3>
					<!--h4 class="p-stock">В наличии: <span>Есть</span></h4-->
					<div class="p-rating">
						<i class="fa fa-star-o"></i>
						<i class="fa fa-star-o"></i>
						<i class="fa fa-star-o"></i>
						<i class="fa fa-star-o"></i>
						<i class="fa fa-star-o"></i>
					</div>
					<div class="input-text-modal">
						{{order_form.errors}}
						{{сustomer_form.errors}}
						<form method="post" action="">
							{% csrf_token %}
							<input type="hidden" name="product" value="{{product.id}}">
							<div class="form-group">
							    <label for="validationTooltipUsername">Пред. осмотр: </label>
							    <span id="preview-content" class="{{product.classes}}"></span>
							    <input type="text" name="preview_text" id="preview-text" class="form-control form-contact"  placeholder="Введите имя или текст ..." required>
							</div>
							{% if product_materials %}
							    <div class="form-group">
								    <label for="exampleFormControlSelect1">Выберите материал:</label>
								    <select name="material" class="form-control product_material form-contact" id="product-material">
								    	{% for  product_material in product_materials %}
								    		<option data-price="{{product_material.price}}" value="{{product_material.id}}">
								    			{{product_material.material.title}}
								    		</option>
								    	{% empty %}
								    		<option value="">Материал не добавлен</option>
								    	{% endfor %}
								    </select>
								  </div>
							  {% endif %}
							  <div class="form-group">
							    <label for="validationTooltipUsername">Введите номер телефона: </label>
							    <span id="preview-content" class="{{product.classes}}"></span>
							    <input type="tel" name="phone_number" class="form-control" id="client-phone" placeholder="номер телефон" required>
							</div>
							<input type="submit" name="" value="Заказать" id="send-message" class="site-btn">
						</form>
					</div>

					<div id="accordion" class="accordion-area">
						<div class="panel">
							<div class="panel-header" id="headingOne">
								<button style="min-height: 50px;" class="panel-link active" data-toggle="collapse" data-target="#collapse1" aria-expanded="true" aria-controls="collapse1">Описание</button>
							</div>
							<div id="collapse1" class="collapse show" aria-labelledby="headingOne" data-parent="#accordion">
								<div class="panel-body">
									<p class="p-text">{{product.description|safe}}</p>
								</div>
							</div>
						</div>
						<div class="panel">
							<div class="panel-header" id="headingTwo">
								<button class="panel-link" data-toggle="collapse" data-target="#collapse2" aria-expanded="false" aria-controls="collapse2">Подробности </button>
							</div>
							<div id="collapse2" class="collapse" aria-labelledby="headingTwo" data-parent="#accordion">
								<div class="panel-body">
									{{product.details|safe}}
								</div>
							</div>
						</div>
						<div class="panel">
							<div class="panel-header" id="headingThree">
								<button class="panel-link" data-toggle="collapse" data-target="#collapse3" aria-expanded="false" aria-controls="collapse3">доставка и возврат</button>
							</div>
							<div id="collapse3" class="collapse" aria-labelledby="headingThree" data-parent="#accordion">
								<div class="panel-body">
									{{product.shipping_return|safe}}
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="col-md-12 spad">
					<div class="frcontainer">
						<div class="row">
							<div class="col-md-4">
								<div class="media">
								  <div class="media-left">
								    <a href="#" class="icon-slaider">
								      <i class="fa fa-diamond" aria-hidden="true"></i>
								    </a>
								  </div>
								  <div class="media-body">
								    <h4 class="media-heading">Неподдельный</h4>
								    Качественные материалы
								  </div>
								</div>
							</div>
							<div class="col-md-4">
								<div class="media">
								  <div class="media-left">
								    <a href="#" class="icon-slaider">
								      <i class="fa fa-shield" aria-hidden="true"></i>
								    </a>
								  </div>
								  <div class="media-body">
								    <h4 class="media-heading">100% безопасность</h4>
								    Оплата
								  </div>
								</div>
							</div>
							<div class="col-md-4">
								<div class="media">
								  <div class="media-left">
								    <a href="#" class="icon-slaider">
								     <i class="fa fa-shopping-bag" aria-hidden="true"></i>
								    </a>
								  </div>
								  <div class="media-body">
								    <h4 class="media-heading">Бесплатная доставка по Казахстану</h4>
								  </div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
{% endblock %}
{% block domready %}
	/* WebSocket begin */
	/*var url = 'ws://' + window.location.host +
	            '/ws/crm/figma/order/'+{{seller.id}}+'/';
	var orderSocket = new WebSocket(url);
	orderSocket.onmessage = function(e) {
	    var data = JSON.parse(e.data);
	    var preview_text = data.preview_text;
	    alert(preview_text)
	};
	orderSocket.onclose = function(e) {
	    console.error('Chat socket closed unexpectedly');
	};

	$(document).on('click', '#send-message', function(){
		alert('test')
		event.preventDefault()
		var product = $('#product').val()
		var preview_text = $('#preview-text').val()
		var product_material = $('#product-material').val()
		var phone_number = $('#client-phone').val()
		orderSocket.send(JSON.stringify(
			{
				'product': product,
				'preview_text': preview_text,
				'product_material': product_material,
				'phone_number': phone_number
			}
		));
	})*/
	/* WebSocket end */
{% endblock %}