stello/crm/urls.py
from django.urls import path
from . import views
app_name = 'crm'
urlpatterns = [
    path('worker/', views.WorkerListView.as_view(), name="worker_list"),
    path('worker/<int:worker_id>', views.WorkerUpdateView.as_view(),
         name="worker_update"),
    path('worker/create/', views.WorkerCreateView.as_view(),
         name="worker_create"),
    path('order/', views.OrderListView.as_view(), name="order"),
    path('order/<int:customer_id>', views.OrderDetailView.as_view(),
         name="order_detail"),
    path('order/create/', views.OrderCreateView.as_view(),
         name="order_create"),
    path('integration/list/', views.IntegrationListView.as_view(),
         name="integration_list"),
    path('integration/create/', views.IntegrationCreateView.as_view(),
         name="integration_create"),
    path('integration/<int:id>', views.IntegrationDetailView.as_view(),
         name="integration_detail"),
    path('report/list/', views.ReportListView.as_view(),
         name="report_list"),
    path('report/list/<int:manager>', views.ReportListView.as_view(),
         name="report_list")
]

stello/stello/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    url('', include('pwa.urls')),
    path('', auth_views.LoginView.as_view(
        redirect_authenticated_user=True),name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),
    path('figma/', include('figma.urls')),
    path('crm/', include('crm.urls')),
    path('social_messenger/', include('social_messenger.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

stello/crm/models.py
from django.utils import timezone
from django.db import models
from django.conf import settings


# Базовый абстрактный класс
class ItemBase(models.Model):
    title = models.CharField(max_length=180)

    class Meta:
        abstract = True

    def __str__(self):
        return self.title


# Список компании
class Сompany(ItemBase):
    pass

    class Meta:
        db_table = "companies"


# Расширенный модель пользователя
class Profile(models.Model):
    TYPE_CHOICES = (
        (1, "Управляющий компанией"),
        (2, "Главный менеджер"),
        (3, "Менеджер"),
        (4, "Бухгалтер"),
        (5, "Курьер"),
    )
    user = models.OneToOneField(settings.AUTH_USER_MODEL,
                                on_delete=models.CASCADE,
                                primary_key=True)
    company = models.ForeignKey(
        Сompany, related_name='profiles_company',
        on_delete=models.CASCADE)
    type = models.IntegerField(default=1, choices=TYPE_CHOICES, null=True)
    phone_number = models.CharField(max_length=18, blank=True)
    address = models.CharField(max_length=280, blank=True)
    is_blocked = models.BooleanField(default=False)
    last_lead = models.DateTimeField(auto_now_add=True)


# Список клиентов
class Сustomer(models.Model):
    TYPE_CHOICES = (
        ("instagramV2", "Instagram direct"),
        ("instagramVOff", "комментарии Instagram"),
        ("whatsapp", "Whatsapp"),
        ("whatsapp2", "Whatsapp Enterprise"),
    )
    company = models.ForeignKey(
        Сompany, related_name='customers_company',
        on_delete=models.CASCADE)
    address = models.CharField(max_length=180, blank=True)
    login = models.CharField(max_length=180)
    type = models.CharField(max_length=80, choices=TYPE_CHOICES, null=True)
    avatar = models.URLField(max_length=380, null=True)
    phone_number = models.CharField(max_length=18, blank=True)
    backup_phone_number = models.CharField(max_length=18, blank=True)
    customer_id = models.IntegerField(null=True)
    social_id = models.CharField(max_length=180, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "customers"

    def __str__(self):
        return self.login


# Список заказов
class Order(models.Model):
    PAYMENT_CHOICES = (
        (1, "Полная оплата"),
        (2, "Предварительная оплата"),
        (3, "Оплата при доставке")
    )
    company = models.ForeignKey(
        Сompany, related_name='orders_company',
        on_delete=models.CASCADE)
    customer = models.ForeignKey(
        Сustomer, related_name='order_customers',
        on_delete=models.CASCADE)
    seller = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    price = models.DecimalField(max_digits=19, decimal_places=0)
    product = models.CharField(max_length=180)
    count = models.IntegerField(default=1)
    deadline_date = models.DateField(null=True)
    payment = models.IntegerField(choices=PAYMENT_CHOICES, default=1)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "orders"


# Список интеграции с соц. мессен.
class Integration(ItemBase):
    TYPE_CHOICES = (
        ("instagramV2", "Instagram direct"),
        ("instagramVOff", "комментарии Instagram"),
        ("whatsapp", "Whatsapp"),
        ("whatsapp2", "Whatsapp Enterprise"),
    )
    TYPE_STATUS = (
        ("active", "Активный"),
        ("blocked", "Блокированный")
    )
    type = models.CharField(max_length=80, choices=TYPE_CHOICES)
    login = models.CharField(max_length=180)
    avatar = models.URLField(max_length=380, null=True, blank=True)
    externalId = models.CharField(max_length=180, null=True)
    api_id = models.IntegerField(blank=True, null=True)
    api_token = models.CharField(max_length=180, null=True)
    status = models.CharField(max_length=12, choices=TYPE_STATUS,
        default="active")
    managers = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True)
    company = models.ForeignKey(
        Сompany, related_name='integration_companies',
        on_delete=models.CASCADE, blank=True, null=True)
    customers = models.ManyToManyField(
        Сustomer, related_name='integrations_customers')

    class Meta:
        db_table = "integrations"

    def __str__(self):
        return self.login


# Статус заказа
class LeadStatus(models.Model):
    title = models.CharField(max_length=180)
    companies = models.ManyToManyField(
        Сompany, through='CompanyLeadStatus', symmetrical=False)

    class Meta:
        db_table = "lead_status"

    def __str__(self):
        return self.title


# Воронка компании
class CompanyLeadStatus(models.Model):
    lead_status = models.ForeignKey(LeadStatus, related_name='lead_status_rel',
                                    on_delete=models.CASCADE)
    company = models.ForeignKey(Сompany, related_name='company_rel',
                                on_delete=models.CASCADE)


# Список обращении
class Lead(models.Model):
    lead_id = models.IntegerField(null=True)
    read = models.BooleanField(default=False)
    company = models.ForeignKey(
        Сompany, related_name='leads_company',
        on_delete=models.CASCADE)
    integration = models.ForeignKey(
        Integration, related_name='leads_integration',
        on_delete=models.CASCADE)
    customer = models.ForeignKey(
        Сustomer, related_name='leads_customer',
        on_delete=models.CASCADE)
    manager = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
        null=True, blank=True
    )
    status = models.ForeignKey(LeadStatus, related_name='leads_status',
                               on_delete=models.CASCADE, null=True, blank=True)
    message_unread = models.IntegerField(default=0)
    real_id = models.IntegerField(null=True)
    is_archive = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    updated_at = models.DateTimeField(null=True, blank=True)

    def save(self, *args, set_updated_at=True, **kwargs):
        if self.pk is not None:
            if set_updated_at:
                self.updated_at = timezone.now()
        super().save(*args, **kwargs)

    class Meta:
        db_table = "leads"

stello/crm/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Order, Сustomer, Profile, Integration


# Форма пользователя
class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = [
            'username', 'password', 'first_name', 'last_name', 'email'
        ]

        def __init__(self, request, *args, **kwargs):
            self.request = request
            super().__init__(*args, **kwargs)

        def save(self, commit=True):
            instance = super().save(commit=False)
            instance.company = self.request.user.profile.company
            if commit:
                instance.save()
            return instance


# Форма работника
class WorkerForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = [
            'phone_number', 'address', 'type', 'is_blocked'
        ]


# Форма заказа
class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = [
            'product', 'count', 'payment', 'deadline_date', 'price'
        ]

    def __init__(self, request, *args, **kwargs):
        self.request = request
        super().__init__(*args, **kwargs)

    def save(self, commit=True):
        instance = super().save(commit=False)
        instance.seller = self.request.user
        instance.company = self.request.user.profile.company
        if commit:
            instance.save()
        return instance


# Форма клиента
class СustomerForm(forms.ModelForm):
    class Meta:
        model = Сustomer
        fields = [
            'login', 'phone_number', 'address', 'backup_phone_number'
        ]

    def __init__(self, request, *args, **kwargs):
        self.request = request
        super().__init__(*args, **kwargs)

    def save(self, commit=True):
        instance = super().save(commit=False)
        instance.company = self.request.user.profile.company
        if commit:
            instance.save()
        return instance


# Форма интеграции
class IntegrationForm(forms.ModelForm):
    class Meta:
        model = Integration
        fields = [
            'type', 'login', 'externalId',  'api_id', 'api_token'
        ]

    def __init__(self, request, *args, **kwargs):
        self.request = request
        super().__init__(*args, **kwargs)

    def save(self, commit=True):
        instance = super().save(commit=False)
        instance.company = self.request.user.profile.company
        if commit:
            instance.save()
        return instance

stello/templates/crm/worker/form.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% load crm_tags %}
{% load message_tags %}
{% block sidebar %}
    {% include "crm/worker/sidebar.html" %}
{% endblock %}
{% block main %}
    <main class="main main-visible" id="MainContent">
        {% if user_form.errors %}
            <ul>
                {% for error in user_form.errors %} 
                      <li>{{ error }}</li>
                {% endfor %}
            </ul>
        {% endif %}  
        {% if worker_form.errors %}
            <ul>
                {% for error in worker_form.errors %} 
                      <li>{{ error }}</li>
                {% endfor %}
            </ul>
        {% endif %}  
        <!-- Profile Settings Start -->
        <div class="profile" style="display: block;">
            <div class="page-main-heading sticky-top py-2 px-3 mb-3">
                <!-- Chat Back Button (Visible only in Small Devices) -->
                <button class="btn btn-secondary btn-icon btn-minimal btn-sm text-muted d-xl-none" type="button" data-close="">
                    <svg class="hw-20" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 19l-7-7m0 0l7-7m-7 7h18"></path>
                      </svg>
                    <!-- <img class="injectable hw-20" src="./../assets/media/heroicons/outline/arrow-left.svg" alt=""> -->
                </button>

                <div class="pl-2 pl-xl-0">
                    <h5 class="font-weight-semibold">Настройки</h5>
                    <p class="text-muted mb-0">Обновить личную информацию и настройки</p>
                </div>
            </div>
            <div class="container-xl px-2 px-sm-3">
                <div>
                    <form action="" method="POST">
                        {% csrf_token %}
                        <div class="card mb-3">
                            <div class="card-header">
                                <h6 class="mb-1">Учетная запись</h6>
                                <p class="mb-0 text-muted small">Обновить личную и контактную информацию</p>
                            </div>
                            
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-md-6 col-12">
                                        <div class="form-group">
                                            <label for="lastName">Фамилия</label>
                                            {{user_form.last_name|add_class:"form-control"}}
                                        </div>
                                    </div>
                                    <div class="col-md-6 col-12">
                                        <div class="form-group">
                                            <label for="firstName">Имя</label>
                                            {{user_form.first_name|add_class:"form-control"}}
                                        </div>
                                    </div>
                                    <div class="col-md-6 col-12">
                                        <div class="form-group">
                                            <label for="firstName">Тип пользователя</label>
                                            {{worker_form.type|add_class:"form-control"}}
                                        </div>
                                    </div>
                                    <div class="col-md-6 col-12">
                                        <div class="form-group">
                                            <label for="mobileNumber">Номер телефона</label>
                                            {{worker_form.phone_number|add_class:"form-control"}}
                                        </div>
                                    </div>
                                    <div class="col-md-6 col-12">
                                        <div class="form-group">
                                            <label for="mobileNumber">Адрес</label>
                                            {{worker_form.address|add_class:"form-control"}}
                                        </div>
                                    </div>
                                    <div class="col-md-6 col-12">
                                        <div class="form-group">
                                            <label for="birthDate">email</label>
                                            {{user_form.email|add_class:"form-control"}}
                                        </div>
                                    </div>
                                    <div class="col-md-6 col-12">
                                        <div class="form-group">
                                            <label for="birthDate">Логин</label>
                                            {{user_form.username|add_class:"form-control"}}
                                        </div>
                                    </div>
                                    <div class="col-md-6 col-12">
                                        <div class="form-group">
                                            <label for="birthDate">Пароль</label>
                                            {{user_form.password|add_class:"form-control"}}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="card mb-3">
                            <div class="card-header">
                                <h6 class="mb-1">Привязка</h6>
                                <p class="mb-0 text-muted small">Привязать данные на аккаунт</p>
                            </div>
                            
                            <div class="card-body p-0">
                                <ul class="list-group list-group-flush list-group-sm-column">    
                                    <li class="list-group-item py-2">
                                        <div class="media align-items-center">
                                            <div class="media-body">
                                                <p class="mb-0">Заблокировать учетную запись</p>
                                            </div>
                                            <div class="custom-control custom-switch mr-2">
                                                {{worker_form.is_blocked|add_class:"custom-control-input"}}
                                                <label class="custom-control-label" for="id_is_blocked">&nbsp;</label>
                                            </div>
                                        </div>
                                    </li>
                                    {% for integration in integrations %}
                                        <li class="list-group-item py-2">
                                        <div class="media align-items-center">
                                            <div class="media-body">
                                                <p class="mb-0">Разрешить доступ для <u>{{integration.login}}</u></p>
                                            </div>
                                            <div class="custom-control custom-switch mr-2">
                                                <input type="checkbox" class="custom-control-input" id="integratedSwitch{{integration.id}}" 
                                                    {% is_integrate integration worker %} name="integration_account" value="{{integration.id}}">
                                                <label class="custom-control-label" for="integratedSwitch{{integration.id}}">&nbsp;</label>
                                            </div>
                                        </div>
                                    </li>
                                    {% endfor %}
                                </ul>
                            </div>

                            <div class="card-footer d-flex justify-content-end">
                                <input type="submit" class="btn btn-primary" name="submit" value="Сохранить изменения">
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <!-- Profile Settings End -->
    </main>
{% endblock %}

stello/templates/crm/worker/list.html
{% extends "base.html" %}
{% load message_tags %}
{% block sidebar %}
    {% include "crm/worker/sidebar.html" %}
{% endblock %}
{% block main %}
    <main class="main" id="MainContent">
        <!-- Profile Settings Start -->
        <div class="profile" style="display: block;">
            <div class="container-xl px-2 px-sm-3">
                <div class="d-flex flex-column justify-content-center text-center vh-100 w-100">
                    <div class="container">
                        <div class="avatar avatar-lg mb-2">
                            <svg height="80" width="80" viewBox="0 0 512 511"><g><path d="m120.65625 512.476562c-7.25 0-14.445312-2.023437-20.761719-6.007812-10.929687-6.902344-17.703125-18.734375-18.117187-31.660156l-1.261719-41.390625c-51.90625-46.542969-80.515625-111.890625-80.515625-183.992188 0-68.816406 26.378906-132.101562 74.269531-178.199219 47.390625-45.609374 111.929688-70.726562 181.730469-70.726562s134.339844 25.117188 181.730469 70.726562c47.890625 46.097657 74.269531 109.382813 74.269531 178.199219 0 68.8125-26.378906 132.097657-74.269531 178.195313-47.390625 45.609375-111.929688 70.730468-181.730469 70.730468-25.164062 0-49.789062-3.253906-73.195312-9.667968l-46.464844 20.5c-5.035156 2.207031-10.371094 3.292968-15.683594 3.292968zm135.34375-471.976562c-123.140625 0-216 89.816406-216 208.925781 0 60.667969 23.957031 115.511719 67.457031 154.425781 8.023438 7.226563 12.628907 17.015626 13.015625 27.609376l.003906.125 1.234376 40.332031 45.300781-19.988281c8.15625-3.589844 17.355469-4.28125 25.921875-1.945313 20.132812 5.554687 41.332031 8.363281 63.066406 8.363281 123.140625 0 216-89.816406 216-208.921875 0-119.109375-92.859375-208.925781-216-208.925781zm-125.863281 290.628906 74.746093-57.628906c5.050782-3.789062 12.003907-3.839844 17.101563-.046875l55.308594 42.992187c16.578125 12.371094 40.304687 8.007813 51.355469-9.433593l69.519531-110.242188c6.714843-10.523437-6.335938-22.417969-16.292969-14.882812l-74.710938 56.613281c-5.050781 3.792969-12.003906 3.839844-17.101562.046875l-55.308594-41.988281c-16.578125-12.371094-40.304687-8.011719-51.355468 9.429687l-69.554688 110.253907c-6.714844 10.523437 6.335938 22.421874 16.292969 14.886718zm0 0" data-original="#000000" class="active-path" data-old_color="#000000" fill="#665dfe"></path></g> </svg>
                        </div>

                        <h5><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Добро пожаловать!</font></font></h5>
                        <p class="text-muted"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
                            Пожалуйста, выберите работника
                        </font></font></p>
                    </div>
                </div>
            </div>
        </div>
        <!-- Profile Settings End -->
    </main>
{% endblock %}

stello/templates/crm/worker/sidebar.html
{% load static %}
{% load crm_tags %}
<!-- Tab Content Start -->
<div class="tab-content">

    <!-- Profile Tab Content Start -->
    <div>
        <div class="d-flex flex-column h-100">
            <div class="hide-scrollbar">
                <!-- Sidebar Header Start -->
                <div class="sidebar-header sticky-top p-2">
                    <h5 class="font-weight-semibold">Профиль</h5>
                    <p class="text-muted mb-0">Личная информация и настройки</p>
                </div>
                <!-- Sidebar Header end -->

                <!-- Sidebar Content Start -->
                <ul class="contacts-list">
                    <li class="contacts-item worker-select">
                        <a class="contacts-link" href="{% url 'crm:worker_create' %}">
                            <div class="contacts-content">
                                <div class="contacts-info">
                                    <h6 class="chat-name text-truncate">Добавить нового работника</h6>
                                </div>
                            </div>
                        </a>
                    </li>
                    <!-- workers Item Start -->
                    {% for value in workers %}
                        <li class="contacts-item worker-select {% is_active value.id worker.id %}" data-id="{{value.id}}">
                            <a class="contacts-link" href="{% url 'crm:worker_update' value.id %}">
                                <div class="avatar">
                                    <img src="{% static 'images/avatar.png' %}" alt="">
                                </div>
                                <div class="contacts-content">
                                    <div class="contacts-info">
                                        <h6 class="chat-name text-truncate">{{value.get_full_name}}</h6>
                                    </div>
                                    <div class="contacts-texts">
                                        <!-- Default :: Inline SVG -->
                                        <svg class="hw-16 text-muted mr-1" viewBox="0 0 20 20" fill="currentColor">
                                            <path fill-rule="evenodd" d="M5.05 4.05a7 7 0 119.9 9.9L10 18.9l-4.95-4.95a7 7 0 010-9.9zM10 11a2 2 0 100-4 2 2 0 000 4z" clip-rule="evenodd"></path>
                                        </svg>
                                            
                                        <!-- Alternate :: External File link -->
                                        <!-- <img class="injectable hw-16 text-muted mr-1" src="./../assets/media/heroicons/solid/location-marker.svg" alt=""> -->
                                        <p class="text-muted mb-0">Алматы</p>
                                    </div>
                                </div>
                            </a>
                        </li>
                    {% endfor %}
                </ul>
                <!-- Sidebar Content End -->

            </div>
        </div>
    </div>
    <!-- Profile Tab Content End -->
</div>
<!-- Tab Content End -->