stello/crm/urls.py
from django.urls import path
from . import views
app_name = 'crm'
urlpatterns = [
    path('worker/', views.WorkerListView.as_view(), name="worker_list"),
    path('worker/<int:worker_id>', views.WorkerUpdateView.as_view(),
         name="worker_update"),
    path('worker/create/', views.WorkerCreateView.as_view(),
         name="worker_create"),
    path('order/', views.OrderListView.as_view(), name="order"),
    path('order/<int:customer_id>', views.OrderDetailView.as_view(),
         name="order_detail"),
    path('order/create/', views.OrderCreateView.as_view(),
         name="order_create"),
    path('integration/list/', views.IntegrationListView.as_view(),
         name="integration_list"),
    path('integration/create/', views.IntegrationCreateView.as_view(),
         name="integration_create"),
    path('integration/<int:id>', views.IntegrationDetailView.as_view(),
         name="integration_detail"),
    path('report/list/', views.ReportListView.as_view(),
         name="report_list"),
    path('report/list/<int:manager>', views.ReportListView.as_view(),
         name="report_list")
]

stello/stello/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    url('', include('pwa.urls')),
    path('', auth_views.LoginView.as_view(
        redirect_authenticated_user=True),name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),
    path('figma/', include('figma.urls')),
    path('crm/', include('crm.urls')),
    path('social_messenger/', include('social_messenger.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

stello/crm/models.py
from django.utils import timezone
from django.db import models
from django.conf import settings


# Базовый абстрактный класс
class ItemBase(models.Model):
    title = models.CharField(max_length=180)

    class Meta:
        abstract = True

    def __str__(self):
        return self.title


# Список компании
class Сompany(ItemBase):
    pass

    class Meta:
        db_table = "companies"


# Расширенный модель пользователя
class Profile(models.Model):
    TYPE_CHOICES = (
        (1, "Управляющий компанией"),
        (2, "Главный менеджер"),
        (3, "Менеджер"),
        (4, "Бухгалтер"),
        (5, "Курьер"),
    )
    user = models.OneToOneField(settings.AUTH_USER_MODEL,
                                on_delete=models.CASCADE,
                                primary_key=True)
    company = models.ForeignKey(
        Сompany, related_name='profiles_company',
        on_delete=models.CASCADE)
    type = models.IntegerField(default=1, choices=TYPE_CHOICES, null=True)
    phone_number = models.CharField(max_length=18, blank=True)
    address = models.CharField(max_length=280, blank=True)
    is_blocked = models.BooleanField(default=False)
    last_lead = models.DateTimeField(auto_now_add=True)


# Список клиентов
class Сustomer(models.Model):
    TYPE_CHOICES = (
        ("instagramV2", "Instagram direct"),
        ("instagramVOff", "комментарии Instagram"),
        ("whatsapp", "Whatsapp"),
        ("whatsapp2", "Whatsapp Enterprise"),
    )
    company = models.ForeignKey(
        Сompany, related_name='customers_company',
        on_delete=models.CASCADE)
    address = models.CharField(max_length=180, blank=True)
    login = models.CharField(max_length=180)
    type = models.CharField(max_length=80, choices=TYPE_CHOICES, null=True)
    avatar = models.URLField(max_length=380, null=True)
    phone_number = models.CharField(max_length=18, blank=True)
    backup_phone_number = models.CharField(max_length=18, blank=True)
    customer_id = models.IntegerField(null=True)
    social_id = models.CharField(max_length=180, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "customers"

    def __str__(self):
        return self.login


# Список заказов
class Order(models.Model):
    PAYMENT_CHOICES = (
        (1, "Полная оплата"),
        (2, "Предварительная оплата"),
        (3, "Оплата при доставке")
    )
    company = models.ForeignKey(
        Сompany, related_name='orders_company',
        on_delete=models.CASCADE)
    customer = models.ForeignKey(
        Сustomer, related_name='order_customers',
        on_delete=models.CASCADE)
    seller = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    price = models.DecimalField(max_digits=19, decimal_places=0)
    product = models.CharField(max_length=180)
    count = models.IntegerField(default=1)
    deadline_date = models.DateField(null=True)
    payment = models.IntegerField(choices=PAYMENT_CHOICES, default=1)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "orders"


# Список интеграции с соц. мессен.
class Integration(ItemBase):
    TYPE_CHOICES = (
        ("instagramV2", "Instagram direct"),
        ("instagramVOff", "комментарии Instagram"),
        ("whatsapp", "Whatsapp"),
        ("whatsapp2", "Whatsapp Enterprise"),
    )
    TYPE_STATUS = (
        ("active", "Активный"),
        ("blocked", "Блокированный")
    )
    type = models.CharField(max_length=80, choices=TYPE_CHOICES)
    login = models.CharField(max_length=180)
    avatar = models.URLField(max_length=380, null=True, blank=True)
    externalId = models.CharField(max_length=180, null=True)
    api_id = models.IntegerField(blank=True, null=True)
    api_token = models.CharField(max_length=180, null=True)
    status = models.CharField(max_length=12, choices=TYPE_STATUS,
        default="active")
    managers = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True)
    company = models.ForeignKey(
        Сompany, related_name='integration_companies',
        on_delete=models.CASCADE, blank=True, null=True)
    customers = models.ManyToManyField(
        Сustomer, related_name='integrations_customers')

    class Meta:
        db_table = "integrations"

    def __str__(self):
        return self.login


# Статус заказа
class LeadStatus(models.Model):
    title = models.CharField(max_length=180)
    companies = models.ManyToManyField(
        Сompany, through='CompanyLeadStatus', symmetrical=False)

    class Meta:
        db_table = "lead_status"

    def __str__(self):
        return self.title


# Воронка компании
class CompanyLeadStatus(models.Model):
    lead_status = models.ForeignKey(LeadStatus, related_name='lead_status_rel',
                                    on_delete=models.CASCADE)
    company = models.ForeignKey(Сompany, related_name='company_rel',
                                on_delete=models.CASCADE)


# Список обращении
class Lead(models.Model):
    lead_id = models.IntegerField(null=True)
    read = models.BooleanField(default=False)
    company = models.ForeignKey(
        Сompany, related_name='leads_company',
        on_delete=models.CASCADE)
    integration = models.ForeignKey(
        Integration, related_name='leads_integration',
        on_delete=models.CASCADE)
    customer = models.ForeignKey(
        Сustomer, related_name='leads_customer',
        on_delete=models.CASCADE)
    manager = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
        null=True, blank=True
    )
    status = models.ForeignKey(LeadStatus, related_name='leads_status',
                               on_delete=models.CASCADE, null=True, blank=True)
    message_unread = models.IntegerField(default=0)
    real_id = models.IntegerField(null=True)
    is_archive = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    updated_at = models.DateTimeField(null=True, blank=True)

    def save(self, *args, set_updated_at=True, **kwargs):
        if self.pk is not None:
            if set_updated_at:
                self.updated_at = timezone.now()
        super().save(*args, **kwargs)

    class Meta:
        db_table = "leads"

stello/crm/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Order, Сustomer, Profile, Integration


# Форма пользователя
class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = [
            'username', 'password', 'first_name', 'last_name', 'email'
        ]

        def __init__(self, request, *args, **kwargs):
            self.request = request
            super().__init__(*args, **kwargs)

        def save(self, commit=True):
            instance = super().save(commit=False)
            instance.company = self.request.user.profile.company
            if commit:
                instance.save()
            return instance


# Форма работника
class WorkerForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = [
            'phone_number', 'address', 'type', 'is_blocked'
        ]


# Форма заказа
class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = [
            'product', 'count', 'payment', 'deadline_date', 'price'
        ]

    def __init__(self, request, *args, **kwargs):
        self.request = request
        super().__init__(*args, **kwargs)

    def save(self, commit=True):
        instance = super().save(commit=False)
        instance.seller = self.request.user
        instance.company = self.request.user.profile.company
        if commit:
            instance.save()
        return instance


# Форма клиента
class СustomerForm(forms.ModelForm):
    class Meta:
        model = Сustomer
        fields = [
            'login', 'phone_number', 'address', 'backup_phone_number'
        ]

    def __init__(self, request, *args, **kwargs):
        self.request = request
        super().__init__(*args, **kwargs)

    def save(self, commit=True):
        instance = super().save(commit=False)
        instance.company = self.request.user.profile.company
        if commit:
            instance.save()
        return instance


# Форма интеграции
class IntegrationForm(forms.ModelForm):
    class Meta:
        model = Integration
        fields = [
            'type', 'login', 'externalId',  'api_id', 'api_token'
        ]

    def __init__(self, request, *args, **kwargs):
        self.request = request
        super().__init__(*args, **kwargs)

    def save(self, commit=True):
        instance = super().save(commit=False)
        instance.company = self.request.user.profile.company
        if commit:
            instance.save()
        return instance

stello/templates/crm/order/detail.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% load static %}
{% block sidebar %}
    {% include "crm/order/sidebar.html" %}
{% endblock %}
{% block main %}
    <main class="main main-visible" id="MainContent">
        <div class="profile" style="display: block;">
            <div class="page-main-heading sticky-top py-2 px-3 mb-3">
                <!-- Chat Back Button (Visible only in Small Devices) -->
                <button class="btn btn-secondary btn-icon btn-minimal btn-sm text-muted d-xl-none" type="button" data-close="">
                    <svg class="hw-20" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 19l-7-7m0 0l7-7m-7 7h18"/>
                      </svg>
                    <!-- <img class="injectable hw-20" src="./../assets/media/heroicons/outline/arrow-left.svg" alt=""> -->
                </button>

                <div class="pl-2 pl-xl-0">
                    <h5 class="font-weight-semibold">Подробнее</h5>
                    <p class="text-muted mb-0">Информация о заказе</p>
                </div>
            </div>
            <form action="" method="POST">
                {% csrf_token %}
                <div class="container-xl px-2 px-sm-3">
                    <div class="row">
                        <div class="col">
                            <div class="card mb-3">
                                <div class="card-header">
                                    <h6 class="mb-1">Учетная запись</h6>
                                    <p class="mb-0 text-muted small">Информация о заказчике</p>
                                </div>
                                
                                <div class="card-body">
                                    <div class="row">
                                        <div class="col-md-4 col-12">
                                            <div class="form-group">
                                                <label for="firstName">Имя</label>
                                                {{customer_form.login|add_class:"form-control"}}
                                            </div>
                                        </div>
                                        <div class="col-md-4 col-12">
                                            <div class="form-group">
                                                <label for="mobileNumber">Мобильный номер</label>
                                                {{customer_form.phone_number|add_class:"form-control"}}
                                            </div>
                                        </div>
                                        <div class="col-md-4 col-12">
                                            <div class="form-group">
                                                <label for="birthDate">Адрес</label>
                                                {{customer_form.address|add_class:"form-control"}}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="card mb-3">
                                <div class="card-header d-flex justify-content-between align-items-center">
                                    <h6 class="mb-1">Список заказов</h6>
                                    <ul class="nav flex-nowrap">                                        
                                        <li class="nav-item list-inline-item mr-0">
                                            <div class="dropdown show">
                                                <a class="nav-link text-muted px-1" href="#" role="button" title="Заказы" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                                                    <!-- Default :: Inline SVG -->
                                                    <svg class="hw-20" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 5v.01M12 12v.01M12 19v.01M12 6a1 1 0 110-2 1 1 0 010 2zm0 7a1 1 0 110-2 1 1 0 010 2zm0 7a1 1 0 110-2 1 1 0 010 2z"></path>
                                                    </svg>
                                                </a>

                                                <div class="dropdown-menu dropdown-menu-right" style="position: absolute; will-change: transform; top: 0px; left: 0px; transform: translate3d(-163px, 40px, 0px);" x-placement="bottom-end">
                                                    <a class="dropdown-item" href="#" role="button" data-toggle="modal" data-target="#createOrder">Создать новый заказ</a>
                                                </div>
                                            </div>
                                        </li>
                                    </ul>
                                </div>
                                
                                <div class="card-body p-0">
                                    <div class="table-responsive-sm">
                                    <table class="table table-bordered table-hover" style="font-size: 0.855rem;"> 
                                        <thead>
                                            <th>Наименование</th>
                                            <th>Количество</th>
                                            <th>Стоимость</th>
                                            <th>Оплата</th>
                                            <th>Срок заказа</th>
                                        </thead>
                                        <tbody>
                                            {% for order in orders %}
                                                <tr>
                                                    <td>{{order.product}}</td>
                                                    <td>{{order.count}}</td>
                                                    <td>{{order.price}}</td>
                                                    <td>{{order.get_status_display}}</td>
                                                    <td>{{order.deadline_date|date:"d.m.Y"}}</td>
                                                </tr>
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>

        </div>
    </main>
{% endblock %}

{% block modal %}
<!-- Modal 2 :: Create Group -->
        <div class="modal modal-lg-fullscreen fade" id="createOrder" tabindex="-1" role="dialog" aria-labelledby="createOrderLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable modal-dialog-zoom">
                <div class="modal-content">
                    <form action="" method="POST">
                        {% csrf_token %}
                        <div class="modal-header">
                            <h5 class="modal-title js-title-step" >Test</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body py-0 hide-scrollbar">
                            <div class="row">
                                <div class="col-12">
                                    <div class="form-group">
                                        <label for="groupName">Наименование заказа</label>
                                        {{order_form.product|add_class:"form-control"}}
                                    </div>
                                </div>
                                <div class="col-12">
                                    <div class="form-group">
                                        <label for="groupName">Количество</label>
                                        {{order_form.count|add_class:"form-control"}}
                                    </div>
                                </div>
                                <div class="col-12">
                                    <div class="form-group">
                                        <label for="groupName">Стоимость</label>
                                        {{order_form.price|add_class:"form-control"}}
                                    </div>
                                </div>
                                <div class="col-12">
                                    <div class="form-group">
                                        <label for="groupName">Оплата</label>
                                        {{order_form.payment|add_class:"form-control"}}
                                    </div>
                                </div>
                                <div class="col-12">
                                    <div class="form-group">
                                        <label for="groupName"> Срок доставки</label>
                                        {{order_form.deadline_date|add_class:"form-control"|attr:"type:date"}}
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <input type="submit" name="order_submit" class="btn btn-primary" value="Сохранить">
                        </div>
                    </form>
                </div>
            </div>
        </div>
{% endblock %}

stello/templates/crm/order/list.html
{% extends "base.html" %}
{% load message_tags %}
{% block sidebar %}
    {% include "crm/order/sidebar.html" %}
{% endblock %}
{% block main %}
    <main class="main" id="MainContent">
        <div class="profile" style="display: block;">
            <div class="container-xl px-2 px-sm-3">
                <div class="d-flex flex-column justify-content-center text-center vh-100 w-100">
                    <div class="container">
                        <div class="avatar avatar-lg mb-2">
                            <svg height="80" width="80" viewBox="0 0 512 511"><g><path d="m120.65625 512.476562c-7.25 0-14.445312-2.023437-20.761719-6.007812-10.929687-6.902344-17.703125-18.734375-18.117187-31.660156l-1.261719-41.390625c-51.90625-46.542969-80.515625-111.890625-80.515625-183.992188 0-68.816406 26.378906-132.101562 74.269531-178.199219 47.390625-45.609374 111.929688-70.726562 181.730469-70.726562s134.339844 25.117188 181.730469 70.726562c47.890625 46.097657 74.269531 109.382813 74.269531 178.199219 0 68.8125-26.378906 132.097657-74.269531 178.195313-47.390625 45.609375-111.929688 70.730468-181.730469 70.730468-25.164062 0-49.789062-3.253906-73.195312-9.667968l-46.464844 20.5c-5.035156 2.207031-10.371094 3.292968-15.683594 3.292968zm135.34375-471.976562c-123.140625 0-216 89.816406-216 208.925781 0 60.667969 23.957031 115.511719 67.457031 154.425781 8.023438 7.226563 12.628907 17.015626 13.015625 27.609376l.003906.125 1.234376 40.332031 45.300781-19.988281c8.15625-3.589844 17.355469-4.28125 25.921875-1.945313 20.132812 5.554687 41.332031 8.363281 63.066406 8.363281 123.140625 0 216-89.816406 216-208.921875 0-119.109375-92.859375-208.925781-216-208.925781zm-125.863281 290.628906 74.746093-57.628906c5.050782-3.789062 12.003907-3.839844 17.101563-.046875l55.308594 42.992187c16.578125 12.371094 40.304687 8.007813 51.355469-9.433593l69.519531-110.242188c6.714843-10.523437-6.335938-22.417969-16.292969-14.882812l-74.710938 56.613281c-5.050781 3.792969-12.003906 3.839844-17.101562.046875l-55.308594-41.988281c-16.578125-12.371094-40.304687-8.011719-51.355468 9.429687l-69.554688 110.253907c-6.714844 10.523437 6.335938 22.421874 16.292969 14.886718zm0 0" data-original="#000000" class="active-path" data-old_color="#000000" fill="#665dfe"></path></g> </svg>
                        </div>

                        <h5><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Добро пожаловать!</font></font></h5>
                        <p class="text-muted"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
                            Пожалуйста, выберите клиента
                        </font></font></p>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

stello/templates/crm/order/sidebar.html
{% load crm_tags %}
<!-- Tab Content Start -->
<div class="tab-content">
    <!-- Profile Tab Content Start -->
    <div>
        <div class="d-flex flex-column h-100">
            <div class="hide-scrollbar">
                <!-- Sidebar Header Start -->
                <div class="sidebar-header sticky-top p-2">

                    <div class="d-flex justify-content-between align-items-center">
                        <!-- Chat Tab Pane Title Start -->
                        <h5 class="font-weight-semibold mb-0">Список заказов</h5>
                        <!-- Chat Tab Pane Title End -->

                        <ul class="nav flex-nowrap">                                        
                            <li class="nav-item list-inline-item mr-0">
                                <div class="dropdown">
                                    <a class="nav-link text-muted px-1" href="#" role="button" title="Заказы" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        <!-- Default :: Inline SVG -->
                                        <svg class="hw-20" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 5v.01M12 12v.01M12 19v.01M12 6a1 1 0 110-2 1 1 0 010 2zm0 7a1 1 0 110-2 1 1 0 010 2zm0 7a1 1 0 110-2 1 1 0 010 2z"></path>
                                        </svg>
                                    </a>

                                    <div class="dropdown-menu dropdown-menu-right" style="">
                                        <a class="dropdown-item" href="#" role="button" data-toggle="modal" data-target="#createOrder">Создать новый заказ</a>
                                    </div>
                                </div>
                            </li>
                        </ul>
                    </div>
                    
                    
                    <!-- Sidebar Header Start -->
                    <div class="sidebar-sub-header">
                        <!-- Sidebar Header Dropdown Start -->
                        <div class="dropdown mr-2">
                            <!-- Dropdown Button Start -->
                            <button class="btn btn-outline-default dropdown-toggle" type="button" data-chat-filter-list="" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Список
                            </button>
                            <!-- Dropdown Button End -->

                            <!-- Dropdown Menu Start -->
                            <div class="dropdown-menu" style="">
                                <a class="dropdown-item" data-chat-filter="" data-select="all-chats" href="#">Саят</a>
                                <a class="dropdown-item" data-chat-filter="" data-select="friends" href="#">Медет</a>
                            </div>
                            <!-- Dropdown Menu End -->
                        </div>
                        <!-- Sidebar Header Dropdown End -->

                        <!-- Sidebar Search Start -->
                        <form class="form-inline">
                            <div class="input-group">
                                <input type="text" class="form-control search border-right-0 transparent-bg pr-0" placeholder="Поиск...">
                                <div class="input-group-append">
                                    <div class="input-group-text transparent-bg border-left-0" role="button">
                                        <!-- Default :: Inline SVG -->
                                        <svg class="text-muted hw-20" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path>
                                        </svg>

                                        <!-- Alternate :: External File link -->
                                        <!-- <img class="injectable hw-20" src="./../assets/media/heroicons/outline/search.svg" alt=""> -->
                                    </div>
                                </div>
                            </div>
                        </form>
                        <!-- Sidebar Search End -->
                    </div>
                    <!-- Sidebar Header End -->
                </div>
                <!-- Sidebar Header end -->

                <!-- Sidebar Content Start -->
                <ul class="contacts-list" id="callLogTab" data-call-list="">
                    <li class="contacts-item">
                        <a class="contacts-link" href="{% url 'crm:order_create' %}">
                            <div class="contacts-content">
                                <div class="contacts-info">
                                    <h6 class="chat-name text-truncate">Добавить новый заказ</h6>
                                </div>
                            </div>
                        </a>
                    </li>
                    {% for value in customers %}
                        <li class="contacts-item {% is_active value.customer.id customer.id %}">
                            <a class="contacts-link" href="{% url 'crm:order_detail' value.customer.id %}">
                                <div class="avatar">
                                    <img src="{{value.customer.avatar}}" alt="">
                                </div>
                                <div class="contacts-content">
                                    <div class="contacts-info">
                                        <h6 class="chat-name text-truncate">{{value.customer.login}}</h6>
                                    </div>
                                    <div class="contacts-texts">
                                        {% for order in value.customer.order_customers.all %}
                                            {{order.product}}; 
                                        {% endfor %}
                                    </div>
                                </div>
                            </a>
                        </li>
                    {% endfor %}                                
                </ul>
                <!-- Sidebar Content End -->
            </div>
        </div>
    </div>
    <!-- Profile Tab Content End -->
</div>
<!-- Tab Content End -->